# Generated by Django 4.2.5 on 2023-09-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_lessonview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='lessonview',
            name='status',
            field=models.CharField(blank=True, default='Не просмотрено', max_length=20),
        ),
    ]
