# Generated by Django 4.2.5 on 2023-09-24 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_productaccess_alter_lessonview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaccess',
            name='access',
            field=models.CharField(choices=[('OPEN', 'Доступен'), ('CLOSE', 'Не доступен')], default='CLOSE', max_length=20),
        ),
        migrations.AddField(
            model_name='productaccess',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productaccess',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
