# Generated by Django 4.2.5 on 2023-09-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productaccess_access_productaccess_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='veiw_time_in_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productaccess',
            name='access',
            field=models.CharField(choices=[('OPEN', 'доступен'), ('CLOSE', 'не доступен')], default='CLOSE', max_length=20),
        ),
    ]
