# Generated by Django 4.2.5 on 2023-09-25 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_veiw_time_in_seconds_lessonview_view_time_in_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='date_of_last_view',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
