# Generated by Django 4.2.5 on 2023-09-26 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_lessonview_date_of_last_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='date_of_last_view',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
